config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,  controllers: {
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords',
    # registrations: 'accounts/registrations',
  }
  resources :accounts, except: :destroy do
    resources :categories, only: [:new, :edit, :update, :destroy, :create]  do 
      resources :images, only: [:create, :edit, :update, :show, :destroy]
    end
    resources :products, only: [:new, :edit, :update, :destroy, :create] do
      resources :images, only: [:create, :edit, :update, :show, :destroy]
    end
    resources :orders, only: [:update, :edit]
  end
  resources :products, only: [:index, :show]
  resources :categories, only: [:index]
  # resources :order_products
  resources :orders, only: [:index, :show]
  # resources :roles

  get '/change_password/:id/new', to: 'accounts#edit_change_password', as: 'change_password'
  post '/change_password/:id', to:'accounts#change_password'

  get '/home', to: 'products#home', as: "home" 
  # post '/change_pass' 
  devise_scope :account do
    root "accounts/sessions#new"
  end
#---------------Ajax---------------
  get '/account_by_role', to: 'accounts#search_accounts_by_role'
  get '/account_by_name', to: 'accounts#search_accounts_by_name'

  get '/products_by_status', to: "products#search_products_by_status"
  get '/products_by_category', to: "products#search_products_by_category"
  get '/products_by_name', to: "products#search_products_by_name"

  get '/categories_by_name', to: "categories#search_categories_by_name"

  get '/orders_by_status', to: 'orders#seach_orders_by_status'
  get '/orders_by_code', to: 'orders#search_orders_by_code'

#---------------Mobile api---------------
  namespace :api do
    namespace :v1 do
      # accounts
      resources :accounts, only: [:edit, :update, :show] 

      post "change_password", to: "accounts#change_password"
      devise_scope :account do
        post "sign_up", :to => 'registrations#create'
        post "sign_in", :to => 'sessions#create'
        post "forgot_password", to: 'passwords#forgot'
        post "reset_password", to: 'passwords#reset'
        # put 'password/update', to: 'password#update'
        delete "sign_out", :to => 'sessions#destroy'
      end
      # order products
      resources :orders, only: [:create, :destroy]
      get 'lists_orders/:account_id/:status', to: 'orders#index_orders_by_account_id' # find list orders by account id and status pending
      get 'order_details/:order_id', to: 'order_products#index_order_products_by_order_id'
      # resources :order_products, only: [:create]
      # categories
      resources :categories, only: [:index]
      get 'search_category_name/:category_name', to: "categories#search_categories_by_name"      
      #products
      resources :products, only: [:show, :index]
      get 'list_products_low_price', to: "products#index_products_by_price" #get low price 
      get 'list_products/:category_id', to: "products#index_products_by_category_id"  #find list product by category id
      get 'products_barcode/:product_key', to: "products#search_barcode"
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
  has_many :order_products
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ActionController::API
  before_action :ensure_params_exist, only: :create
  before_action :check_quantity, only: :create
  respond_to :json

  def create
    order_detail = params[:order_product]
    code = Random.new
    # get account user buy
    @user = Account.find_by_id(params[:order][:account_id])
    @order = Order.new

    # cal total price, total quantity in order
    price = 0
    quantity = 0
    order_detail.each_with_index do |detail|
      quantity += detail[:quantity]
      price += detail[:price] * detail[:quantity]
    end

    params[:order][:code] = code.rand(1000000...9999999).to_s  # random code order
    params[:order][:total_price] = price
    params[:order][:total_quantity] = quantity
    @order = @user.orders.build(order_params)

    t = Array.new # json reponse
    if @order.save
      order_detail.each_with_index do |detail, index|
        @order_product = @order.order_products.create!(product_id: detail[:product_id],
          quantity: detail[:quantity], price: detail[:price])
        t[index] = @order_product
        #update new quantity in Product
        product = Product.find_by_id(detail[:product_id])
        quantity = product.quantity - detail[:quantity]
        product.update_attributes(quantity: quantity)
      end
    end

    render json: {order: @order, order_product: t}
  end

  def index_orders_by_account_id
    if params[:account_id] || params[:status]
      @orders = Order.where(account_id: params[:account_id], status: params[:status])
      return render json: {errors: 'Not found'}, status: 404 if @orders.size < 1
      render json: @orders.as_json
    end 
  end

  def destroy
    if params[:id]
      order = Order.where(id: params[:id], status: 'pending')
      return render json: {errors: 'Not found'}, status: 404 if order.size < 1
      order_products = OrderProduct.where(order_id: params[:id])
      order_products.each do |details|
        product = Product.find_by_id(details.product_id)
        puts 'product'
        puts product.quantity
        puts details.quantity
        requantity = product.quantity + details.quantity
        puts 'new quantity'
        puts requantity
        product.update_attributes(quantity: requantity)
      end
      
      order_products.destroy_all
      order.destroy_all
      render json: {message: 'Canceled order successfully'}
    end
    
  end
  

  protected
  def ensure_params_exist
    if params[:order][:address_ship].blank? || params[:order][:account_id].blank? || params[:order_product].size < 1
      render json: {success: false, message: "missing orders parameter"}, status: 422 
    end
    
  end

  # check quantity in db have enough amount, price json is match with db?
  def check_quantity
    order_detail = params[:order_product]
    order_detail.each_with_index do |detail|
      product = Product.find_by_id(detail[:product_id])
      return render json: product.as_json.merge({success: false}).to_json if product.quantity - detail[:quantity] < 0 || detail[:quantity] < 1
      return render json: {success: false, message: "price not match"} if product.price != detail[:price]
    end
  end

  private
  def order_params
    params.require(:order).permit(:code, :payment_date, 
      :address_ship, :total_price, :status, 
      :total_quantity, :account_id, :cashier_id)
  end

  def order_product_params
    params.require(:order_product).permit(:price, :quantity, :reason, 
      :status, :order_id, :product_id)
  end
end




  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all.page(params[:page]).per(5)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find_by_id(params[:id])
    @account = Account.find_by_id(@order.account_id)
    @order_products = OrderProduct.where(order_id: @order.id)
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_path, notice: 'Order was successfully updated.' }
        format.json { render :index, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def seach_orders_by_status
    if params[:status]
      @orders = Order.where(status: params[:status])
      result = Array.new
      @orders.each do |t|
        result.push({id: t.id, code: t.code, cus_name: Account.find_by_id(t.account_id).name,
          status: t.status, total_price: t.total_price})
      end
      render json: result.to_json
    end

  end
  
  def search_orders_by_code
    if params[:code]
      # pg like
      @orders = Order.where("code ILIKE ?", "%#{params[:code]}%")
      result = Array.new
      @orders.each do |t|
        result.push({id: t.id, code: t.code, cus_name: Account.find_by_id(t.account_id).name,
          status: t.status, total_price: t.total_price})
      end
      render json: result.to_json
    end
  
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:code, :payment_date, :address_ship, :total_price, :status, :total_quantity, :cashier_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="wrap-index-category">
  <div class="title-index-category mb-4">
    All Orders
  </div>
  <%= paginate @orders, theme: 'twitter-bootstrap-4' %>
<%= form_with(model: @order, local: true, method: 'get') do |form| %>
  <div class="row mb-4">
    <!--SORT by status-->
    <div class="col-lg-3 mt-2">
      <%= form.select :status, [['Pending', 'pending'], ['Payment', 'payment']], {prompt: 'Find By Status'}, id: 'select_order_status',class:"filter-select-index-product input-filter-index-category custom-select"%>
    </div>
    <div class="col-lg-4 mt-2"></div>
    <!--input for SEARCH name-->
    <div class="col-lg-3 mt-2">
      <%= form.text_field :search_name, placeholder: "Search Code Order", class:"input-filter-index-category", id: 'txt_search_name' %>
    </div>
    <!--submit bnt-->
    <div class="col-lg-2 mt-2 text-center">
      <%= form.button 'Find', type: 'button', class: "bnt-index-category", id:"M-btn-order-search"%>
    </div>
  </div>
<% end %>
  
  <div class="wrap-table-category">
    <div style="min-width: 700px;">
      <!--LABEL-->
      <div class="row pb-2 wrap-label-index-category">
        <!--ID-->
        <div class="col-1 px-2 text-center label-index-category">ID</div>
        <!--CODE-->
        <div class="col-1 pl-1 text-center label-index-category">Code</div>
        <!--CUSTOMER NAME-->
        <div class="col-3 pl-4 label-index-category">Customer's Name</div>
        <!--TOTAL-->
        <div class="col-1 px-1 text-center label-index-category">Total</div>
        <!--CURRENT STATUS-->
        <div class="col-2 text-center label-index-category">Current Status</div>
        <!--CHANGE STATUS-->
        <div class="col-2 px-1 text-center label-index-category">Show</div>
        <!--ACTION-->
        <div class="col-2 pl-0 pr-3 text-center label-index-category">Pay Order</div>
      </div>
      <!--content-->
      <% @orders.each_with_index do |order, index| index += 1 %>
        <div class="row py-3 wrap-content-index-category content-index-order M-test" >
          <!--ID-->
          <div class="col-1 px-2 text-center"><%= index %></div>
          <!--CODE-->
          <div class="col-1 pl-1 text-center"><%= order.code %></div>
          <!--CUSTOMER NAME-->
          <div class="col-3 pl-4"><%= Account.find_by_id(order.account_id).name %></div>
          <!--TOTAL-->
          <div class="col-1 px-1 text-center"><%= order.total_price %></div>
          <!--CURRENT STATUS-->
          <!--accept: #31C55B ; cancel: #E53348-->
          <div class="col-2 text-center">
          <% if order.status == 'pending' %>
            <span class="order-status" style="background-color: #F6AC43;">Pending</span>
          <% else %>      
            <span class="order-status" style="background-color: #008AFF;">Payment</span>
          <% end %>
          </div>
          <!--CHANGE STATUS-->
          <div class="col-2 px-1 text-center" style="font-size: 15px;">
            <!-- <select class="custom-select" style="width: 90%;">
              <option>Accepted</option>
            </select> -->
            <%= link_to order_path(order) do %>
              <i class="fa fa-search-plus show-bnt-index-account align-items-center" style="width: 70%;"></i>
            <% end %>
          </div>
          <!--ACTION-->
          <div class="col-2 pl-0 text-center pr-3">
          <% if order.status != 'payment' %>
            <%= link_to account_order_path(current_account, order, order: {status: 'payment', cashier_id: current_account.id}), method: :put  do %>
              <button class="bnt-payment-order" style="width: 70%;">Payment</button>
            <% end %>  
          <% else %>
            <%#= link_to account_order_path(current_account, order, order: {status: 'pending', cashier_id: current_account.id}), method: :put do %>
              <!--<button class="bnt-pending-order" style="width: 70%;">Pending</button>-->
            <%# end %>  
          <% end %>
          </div>
        </div>
      <% end %>
      <div id="M-result"></div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    var element = document.getElementsByClassName("content-index-order");

    var i;
    for (i = 0; i < element.length; i++) {
      if (i % 2 != 0) {
        $(element[i]).css("background-color", "#F4F3EF");
      }
    }
  })
$(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});
</script>

app/views/orders/show.html.erb
<!--use css of index categories-->
<p id="notice"><%= notice %></p>
<div class="wrap-index-category">
  <div class="title-index-category mb-4">
    Invoice #<%= @order.code %>
  </div>

  <div class="row">
    <div class="col-12 text-center title-show-order">SSM Market</div>
  </div>

  <div class="row mt-2" style="margin: 0 3%;">
    <!--Customer's Name-->
    <div class="col-md-6 text-left">
      Customer's Name: <span><%= @account.name %></span>
    </div>
    <!--Order Date-->
    <div class="col-md-6 order-right">
      Order Created: <span><%= @order.created_at.strftime("%H:%M, %a %b %d %y") %></span>
    </div>
  </div>

  <div class="row" style="margin: 0 3%;">
    <!--Phone-->
    <div class="col-md-6 text-left">
      Phone: <span><%= @account.phone %></span>
    </div>
    <!--Status-->
    <div class="col-md-6 order-right">
      Status: 
      
      <% if @order.status == 'payment' %>
      <span class="order-status" style="background-color: #008AFF; font-size: 14px;">
      <%= @order.status.capitalize %></span>
      <% else %>
        <span class="order-status" style="background-color: #F6AC43; font-size: 14px;">
        <%= @order.status.capitalize %></span>
      <% end %>
      
      
    </div>
  </div>

  <div class="row" style="margin: 0 3%;">
    <!--Store Address-->
    <div class="col-12 text-left">
      Store Address: <span>Quang Trung Software Center</span>
    </div>
  </div>

  <div class="order-table">
    <div class="row mt-4 wrap-table-show-order" style="margin: 0 3%; min-width: 640px;">
      <div class="col-12">
        <div class="row wrap-label-show-order">
          <!--PID-->
          <div class="col-1 text-center">#</div>
          <!--Code-->
          <!-- <div class="col-2 text-center">Code</div> -->
          <!--Name-->
          <div class="col-3 text-center">Name</div>
          <!--Quantity-->
          <div class="col-2 text-center">Quantity</div>
          <!--Unit Price-->
          <div class="col-3 text-center">Unit Price</div>
          <!--Subtotal-->
          <div class="col-3 text-center">Subtotal</div>
        </div>
      <% @order_products.each_with_index do |detail, index| index += 1 %>
        <div class="row content-show-order">
          <!--PID-->
          <div class="col-1 text-center detail-content-show-order"><%= index %></div>
          <!--Code-->
          <!-- <div class="col-2 text-center detail-content-show-order">9999999</div> -->
          <!--Name-->
          <div class="col-3 text-center detail-content-show-order"><%= Product.find_by_id(detail.product_id).name %></div>
          <!--Quantity-->
          <div class="col-2 text-center detail-content-show-order"><%= detail.quantity %></div>
          <!--Unit Price-->
          <div class="col-3 text-center detail-content-show-order"><%= detail.price %></div>
          <!--Subtotal-->
          <div class="col-3 text-center detail-content-show-order"><%= detail.quantity * detail.price %></div>
        </div>
      <% end %>

        <div class="row wrap-total-show-order">
          <div class="col-1 text-center"></div>
          <!-- <div class="col-2 text-center"></div> -->
          <div class="col-3 text-center"></div>
          <div class="col-2 text-center"></div>
          <div class="col-3 text-center">Total</div>
          <div class="col-3 text-center"><%= @order.total_price %></div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function() {
    var element = document.getElementsByClassName("content-show-order");

    var i;
    for (i = 0; i < element.length; i++) {
      if (i % 2 != 0) {
        $(element[i]).css("background-color", "#F4F3EF");
      }
    }
  })
</script>