config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,  controllers: {
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords',
    # registrations: 'accounts/registrations',
  }
  resources :accounts, except: :destroy do
    resources :categories, only: [:new, :edit, :update, :destroy, :create]  do 
      resources :images, only: [:create, :edit, :update, :show, :destroy]
    end
    resources :products, only: [:new, :edit, :update, :destroy, :create] do
      resources :images, only: [:create, :edit, :update, :show, :destroy]
    end
    resources :orders, only: [:update, :edit]
  end
  resources :products, only: [:index, :show]
  resources :categories, only: [:index]
  # resources :order_products
  resources :orders, only: [:index, :show]
  # resources :roles

  get '/change_password/:id/new', to: 'accounts#edit_change_password', as: 'change_password'
  post '/change_password/:id', to:'accounts#change_password'

  get '/home', to: 'products#home', as: "home" 
  # post '/change_pass' 
  devise_scope :account do
    root "accounts/sessions#new"
  end
#---------------Ajax---------------
  get '/account_by_role', to: 'accounts#search_accounts_by_role'
  get '/account_by_name', to: 'accounts#search_accounts_by_name'

  get '/products_by_status', to: "products#search_products_by_status"
  get '/products_by_category', to: "products#search_products_by_category"
  get '/products_by_name', to: "products#search_products_by_name"

  get '/categories_by_name', to: "categories#search_categories_by_name"

  get '/orders_by_status', to: 'orders#seach_orders_by_status'
  get '/orders_by_code', to: 'orders#search_orders_by_code'

#---------------Mobile api---------------
  namespace :api do
    namespace :v1 do
      # accounts
      resources :accounts, only: [:edit, :update, :show] 

      post "change_password", to: "accounts#change_password"
      devise_scope :account do
        post "sign_up", :to => 'registrations#create'
        post "sign_in", :to => 'sessions#create'
        post "forgot_password", to: 'passwords#forgot'
        post "reset_password", to: 'passwords#reset'
        # put 'password/update', to: 'password#update'
        delete "sign_out", :to => 'sessions#destroy'
      end
      # order products
      resources :orders, only: [:create, :destroy]
      get 'lists_orders/:account_id/:status', to: 'orders#index_orders_by_account_id' # find list orders by account id and status pending
      get 'order_details/:order_id', to: 'order_products#index_order_products_by_order_id'
      # resources :order_products, only: [:create]
      # categories
      resources :categories, only: [:index]
      get 'search_category_name/:category_name', to: "categories#search_categories_by_name"      
      #products
      resources :products, only: [:show, :index]
      get 'list_products_low_price', to: "products#index_products_by_price" #get low price 
      get 'list_products/:category_id', to: "products#index_products_by_category_id"  #find list product by category id
      get 'products_barcode/:product_key', to: "products#search_barcode"
    end
  end

end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :account
  # belongs_to :product
  has_many :images
  validates :name, uniqueness:  {message: 'Name had already!'}, on: [:create,:update]
end

app/controllers/api/v1/categories_controller.rb
class Api::V1::CategoriesController < ActionController::API
  
  def index
    h = Hash.new
    results = Array.new
    @categories = Category.where(status: 'active').includes(:images)
    @categories.each do |c|
      results.push({id: c.id, name: c.name, url: c.images.first.url.url})
    end
    h[:categories] = results
    render json: h.as_json
  end
  
  def search_categories_by_name
    h = Hash.new
    results = Array.new
    # pg like
    @categories = Category.includes(:images).where("name ILIKE ?", "%#{params[:category_name]}%").where(status:'active')
    if @categories.size < 1
      render json: {errors: 'Not found'}, status: 404
    else
      @categories.each do |c|
        results.push({id: c.id, name: c.name, url: c.images.first.url.url})
      end
      h[:categories] = results
      render json: h.as_json
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!
  # GET /categories
  # GET /categories.json
  def index
    
    @categories = Category.all.includes(:images).page(params[:page]).per(5)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
    @image = @category.images.build
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @user = current_account
    # @category = Category.new(category_params)
    @category = @user.categories.build(category_params)
    respond_to do |format|
      if @category.save
        unless params[:images].nil?
          params[:images]['url'].each do |img|
            @image = @category.images.create!(url: img, category_id: @category.id)
          end
        end
        format.html { redirect_to categories_path, notice: 'Category was successfully created.' }
        format.json { render :index, status: :created, location: @category }  
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        unless params[:images].nil?
          params[:images]['url'].each do |i|
            @image = @category.images.create!(url: i, category_id: @category.id)
          end
        end
        unless params[:images_delete].nil?
          params[:images_delete].each do |i|
            image = Image.find(i['id'])
            @category.images.destroy(image)
          end
        end
        format.html { redirect_to categories_path, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_categories_by_name
    if params[:name]
      # pg like
      @categories = Category.where("name ILIKE ?", "%#{params[:name]}%")
      result = Array.new
      @categories.each do |t|
        result.push({id: t.id, name: t.name, image: t.images.first.url.url, status: t.status,
          count_products: Product.where(category_id: t.id).count(:name)})
      end
      render json: result.to_json
    end
    
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :status)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<%= form_with(model: @category, local: true, url:{action: "update"}, html: {id:"form--add--cate"}) do |form| %>
  <div class="wrap-new-category">
    <p class="label-new-category">Edit Category</p>
    <div class="field-new-category">
      <%= form.label :name, class: "label-form-new-category" %><br>
      <%= form.text_field :name, id: :category_name, class:"w-100" %>
      <p class="validate-new-product" id="error--name--cate" style="color: red;"><%= @category.errors[:name].first %></p>
    </div>
    <div class="field-new-category">
      <%= form.label :status, class: "label-form-new-category" %><br>
      <%= form.select :status, [['Active', 'active'], ['Hidden', 'hidden']], {}, id: :category_status, class: 'input-filter-index-category custome-select w-100' %>
    </div>
    <div class="row mt-2 justify-content-center" id="category_img_field_container"> 
       <div class="M-img-field">
          <button class='btn btn-dark M-btn-image'><i class="fa fa-image fa-3x"></i></br>Add Image
          </button>
           <%= form.file_field :images, multiple: false, name: "images[url][]", class: "M-image-input", onchange:"previewImages(event)" %>
          <div class="M-image-output" style="background-image: url('<%= asset_url @category.images.first.url%>'); display:block;">
            <div class='btn btn-light M-image-remove' onclick='removeImages(event, <%= @category.images.first.id%>)'><i class="fa fa-trash"></i></div>
          </div>
        </div>
    </div>
    <p class="validate-new-product text-center" id="error--pic--cate"></p>
    <div class="actions mt-5 text-center">
      <%= form.submit class: "submit-bnt-new-category", style:"min-width: 150px;" %>
    </div>
  </div>
<% end %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<div class="wrap-index-category">
  <div class="title-index-category mb-4">
    View All Categories
  </div>
  <%= paginate @categories, theme: 'twitter-bootstrap-4' %>
  <!--Filter form-->
  <%= form_with(model: @product, local: true, method: 'get', class:"filter-index-categories mb-4") do |form| %>
    <div class="row">
      <!--input for FILTER-->
      <div class="col-lg-5">
        <%= form.text_field :search_name, placeholder:"Name...", class:"input-filter-index-category", id: 'txt_search_cate'%>
      </div>

      <!--FILTER bnt-->
      <div class="col-lg-2 mt-2 text-center">
        <%= form.button 'Find', type: 'button', class: 'bnt-index-category', id: 'M-btn-search-cates' %>
      </div>
    </div>
  <% end %>
  
  <div class="wrap-table-category"><!--.wrap-table in P-index-category file-->
    <div style="min-width: 650px;">
      <!--label for table-->
      <div class="row pb-2 wrap-label-index-category">
        <!--STT-->
        <div class="col-2 text-center label-index-category">No</div>
        <!--IMG-->
        <div class="col-2 text-center label-index-category">Image</div>
        <!--NAME-->
        <div class="col-4 label-index-category">Name</div>
        <!--Total Of Products-->
        <div class="col-2 text-center label-index-category">Total Of Products</div>
        <!--Edit-->
        <div class="col-1 text-center label-index-category">Edit</div>
      </div>

      <!--content of table-->
      <% @categories.each.with_index do |category, index| index += 1 %>
        <div class="row py-3 wrap-content-index-category content-index-category M-test">
          <!--STATUS-->
          <div class="col-2 text-center" ><%= index %></div>
          <!--IMG-->
          <div class="col-2"><img src="<%= category.images.first.url %>" alt="" class="img-index-categories"></div>
          <!--NAME-->
          <div class="col-4"><%= category.name %></div>
          <!--Total Of Products-->
          <div class="col-2 text-center">
            <%= Product.where(category_id: category.id).count(:name) %>
          </div>
          
          <!--Active-->
          <% if category.status == 'active' %>
            <div class="col-1">
              <center>
              <%= link_to edit_account_category_path(current_account, category) do %>
                <button class="edit-bnt-index-category text-center"><i class="fa fa-edit"></i></button>
              <% end %>
              </center>
            </div>
          <% else %>
          <!--Lock-->
          <div class="col-1">
            <center>
            <%= link_to edit_account_category_path(current_account, category) do %>
              <button class="edit-bnt-index-category"><i class="fa fa-lock"></i></center></button>
            <% end %>
            </center>
          </div>
          <% end %>
        </div> 
      <% end %>
      <div id="M-result"></div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    var element = document.getElementsByClassName("content-index-category");

    var i;
    for (i = 0; i < element.length; i++) {
      if (i % 2 != 0) {
        $(element[i]).css("background-color", "#F4F3EF");
      }
    }
  })
  $(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});
</script>

app/views/categories/new.html.erb
<%= form_with(model: @category, local: true, url:{action: "create"}, html: {id:"form--add--cate"}) do |form| %>
  <div class="wrap-index-category wrap-new-category">
    <p class="label-new-category">New Category</p>
    <div class="field-new-category">
      <%= form.label :name, class: "label-form-new-category" %><br>
      <%= form.text_field :name, id: :category_name, style:"width: 100%;" %>
      <p class="validate-new-product" id="error--name--cate" style="color: red;"><%= @category.errors[:name].first %></p>
    </div>

  <div class="row mt-2 justify-content-center" id="category_img_field_container">
      <%= form.fields_for :images do |i| %>
        <div class="M-img-field">
          <button class='btn btn-dark M-btn-image'><i class="fa fa-image fa-3x"></i></br>Add Image
          </button>
           <%= i.file_field :url, multiple: false, name: "images[url][]", class: "M-image-input", onchange:"previewImages(event)" %>
          <div class="M-image-output" id="img__new_category" style="color: black;">
            <div class='btn btn-light M-image-remove' onclick='removeImages(event)'><i class="fa fa-trash"></i></div>
          </div>
        </div>
      <% end %>
    </div>
    <p class="validate-new-product text-center" id="error--pic--cate"></p> 

    <div class="actions mt-5 text-center">
      <%= form.submit class: "submit-bnt-new-category", style:"min-width: 150px;" %>
    </div>
  </div>
<% end %>