config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,  controllers: {
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords',
    # registrations: 'accounts/registrations',
  }
  resources :accounts, except: :destroy do
    resources :categories, only: [:new, :edit, :update, :destroy, :create]  do 
      resources :images, only: [:create, :edit, :update, :show, :destroy]
    end
    resources :products, only: [:new, :edit, :update, :destroy, :create] do
      resources :images, only: [:create, :edit, :update, :show, :destroy]
    end
    resources :orders, only: [:update, :edit]
  end
  resources :products, only: [:index, :show]
  resources :categories, only: [:index]
  # resources :order_products
  resources :orders, only: [:index, :show]
  # resources :roles

  get '/change_password/:id/new', to: 'accounts#edit_change_password', as: 'change_password'
  post '/change_password/:id', to:'accounts#change_password'

  get '/home', to: 'products#home', as: "home" 
  # post '/change_pass' 
  devise_scope :account do
    root "accounts/sessions#new"
  end
#---------------Ajax---------------
  get '/account_by_role', to: 'accounts#search_accounts_by_role'
  get '/account_by_name', to: 'accounts#search_accounts_by_name'

  get '/products_by_status', to: "products#search_products_by_status"
  get '/products_by_category', to: "products#search_products_by_category"
  get '/products_by_name', to: "products#search_products_by_name"

  get '/categories_by_name', to: "categories#search_categories_by_name"

  get '/orders_by_status', to: 'orders#seach_orders_by_status'
  get '/orders_by_code', to: 'orders#search_orders_by_code'

#---------------Mobile api---------------
  namespace :api do
    namespace :v1 do
      # accounts
      resources :accounts, only: [:edit, :update, :show] 

      post "change_password", to: "accounts#change_password"
      devise_scope :account do
        post "sign_up", :to => 'registrations#create'
        post "sign_in", :to => 'sessions#create'
        post "forgot_password", to: 'passwords#forgot'
        post "reset_password", to: 'passwords#reset'
        # put 'password/update', to: 'password#update'
        delete "sign_out", :to => 'sessions#destroy'
      end
      # order products
      resources :orders, only: [:create, :destroy]
      get 'lists_orders/:account_id/:status', to: 'orders#index_orders_by_account_id' # find list orders by account id and status pending
      get 'order_details/:order_id', to: 'order_products#index_order_products_by_order_id'
      # resources :order_products, only: [:create]
      # categories
      resources :categories, only: [:index]
      get 'search_category_name/:category_name', to: "categories#search_categories_by_name"      
      #products
      resources :products, only: [:show, :index]
      get 'list_products_low_price', to: "products#index_products_by_price" #get low price 
      get 'list_products/:category_id', to: "products#index_products_by_category_id"  #find list product by category id
      get 'products_barcode/:product_key', to: "products#search_barcode"
    end
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :account
  has_many :images
  accepts_nested_attributes_for :images #upload img
  has_one :category

  validates :product_key, uniqueness:  {message: 'Product Key had already!'}, on: [:create,:update]
end

app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < ActionController::API
  
  def index_products_by_category_id
    h = Hash.new
    results = Array.new
    @lists = Product.includes(:images).where(category_id: params[:category_id], status: 'active')

    if @lists.size < 1
      render json: {errors: 'Not found'}, status: 404
    else
      @lists.each do |p|
        results.push({id: p.id, name: p.name, url: p.images.first.url.url, 
          product_key: p.product_key, quantity: p.quantity, manufacturer: p.manufacturer,
          manu_date: p.manu_date, expired_date: p.expired_date, description: p.description,
          price: p.price, status: p.status, category_id: p.category_id
        })
      end
      h[:products] = results
      render json: h.as_json
    end
  end

  def index
    h = Hash.new
    t = Array.new
    @products = Product.includes(:images).where(status: 'active').order(:created_at).last(4)
    @products.each do |p|
      cate_name = Category.find(p.category_id).name
      t.push({id: p.id, name: p.name, url: p.images.first.url.url, 
        product_key: p.product_key, quantity: p.quantity, manufacturer: p.manufacturer,
        manu_date: p.manu_date, expired_date: p.expired_date, description: p.description,
        price: p.price, status: p.status, category_id: p.category_id, category_name: cate_name
      })
    end
    h[:products] = t
    render json: h.as_json
  end

  def index_products_by_price
    h = Hash.new
    t = Array.new
    @products = Product.includes(:images).where(status: 'active').order(price: :asc).take(8)

    @products.each do |p|
      cate_name = Category.find(p.category_id).name
      t.push({id: p.id, name: p.name, url: p.images.first.url.url, 
        product_key: p.product_key, quantity: p.quantity, manufacturer: p.manufacturer,
        manu_date: p.manu_date, expired_date: p.expired_date, description: p.description,
        price: p.price, status: p.status, category_id: p.category_id, category_name: cate_name
      })
    end

    h[:products] = t
    render json: h.as_json
  end


  def show
    product = Product.find_by_id(params[:id])
    name = Category.find(product.category_id).name
    unless product.nil?
      render json: product.as_json.merge({category_name: name}).to_json, status: 200 
      return      
    end
    render json: {errors: 'Not found'}, status: 404
  end

  def search_barcode
    product = Product.find_by_product_key(params[:product_key])
    name = Category.find(product.category_id).name
    img = Image.find_by_product_id(product.id).url.url
    unless product.nil?
      render json: product.as_json.merge({category_name: name, url: img}).to_json, status: 200 
      return      
    end
    render json: {errors: 'Not found'}, status: 404
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!

  def home
    @products = Product.all.size
    @orders = Order.all
    @revenue = 0
    @orders.each do |p|
      @revenue += p.total_price
    end
    @users = Account.all.size

    id = OrderProduct.order("quantity DESC").take(3).pluck(:product_id).uniq
 
    @best_products = Product.where(id: id)
    # @best_products.each do |pid|
    #   @p = OrderProduct.where(product_id: pid)
    #   q = 0
    #   @p.each do |i|
    #     q += i.quantity
    #   end
    #   puts q
    # end 

    # vip customer
    money = 0
    vip_id = Order.order("total_price DESC").take(3).pluck(:account_id).uniq
    @vip_customers = Account.where(id: vip_id)
    # @vip_customers.each do |cus|
    #   @t = Order.where(account_id: cus.id)
    #   @t.each do |i|
    #     money += i.total_price
    #   end
    #   # puts money
    # end
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.all.page(params[:page]).per(5)
    @categories = Category.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @categories = Category.all
    @product = Product.new
    @image = @product.images.build
  end

  # GET /products/1/edit
  def edit
    @categories = Category.all
  end

  # POST /products
  # POST /products.json
  def create
    @categories = Category.all
    @user = current_account
    # @product = Product.new(product_params)
    @product = @user.products.build(product_params)
    
    respond_to do |format|
      if @product.save
        unless params[:images].nil?
          params[:images]['url'].each do |img|
            @image = @product.images.create!(url: img, product_id: @product.id)
          end
        end
        format.html { redirect_to product_path(@product), notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @categories = Category.all
    respond_to do |format|
      if @product.update(product_params)
        unless params[:images].nil?
          params[:images]['url'].each do |i|
            @image = @product.images.create!(url: i, product_id: @product.id)
          end
        end
        unless params[:images_delete].nil?
          params[:images_delete].each do |i|
            image = Image.find(i['id'])
            @product.images.destroy(image)
          end
        end
        format.html { redirect_to product_path(@product), notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end 
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search_products_by_status
    if params[:status]
      @products = Product.where(status: params[:status])
      result = Array.new
      @products.each do |t|
        result.push({id: t.id, name: t.name, quantity: t.quantity, 
          status: t.status, category_name: Category.find_by_id(t.category_id).name })
      end
      render json: result.to_json
    end
  end

  def search_products_by_category
    if params[:category_id]
      @products = Product.where(category_id: params[:category_id])      
      result = Array.new
      
      @products.each do |t|
        result.push({id: t.id, name: t.name, quantity: t.quantity, 
          status: t.status, category_name: Category.find_by_id(params[:category_id]).name })
      end
      # puts result.to_json
      render json: result.to_json
    end
  end

  def search_products_by_name
    if params[:name]
      # pg like
      @products = Product.where("name ILIKE ?", "%#{params[:name]}%")
      result = Array.new
      @products.each do |t|
        result.push({id: t.id, name: t.name, quantity: t.quantity, 
          status: t.status, category_name: Category.find_by_id(t.category_id).name })
      end

      render json: result.to_json
    end
  end
  
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:product_key, :name, :quantity, :manufacturer, 
        :manu_date, :expired_date, :description, :price, :status, :category_id, :updater_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<div class="wrap-new-product">
  <%= form_with(model: @product, local: true, url: {action: 'update'}, html: {id:"form--new--product"}) do |form| %>
    <div class="new-product-title mb-3">
      Edit Product
    </div>
    
    <div class="row mb-4">
      <div class="col-lg-12">
        <div class="row">
          <!--label for NAME-->
          <div class="col-lg-12 label-new-product">
            <%= form.label :name %>
          </div>
        </div>

        <div class="row">
          <!--input for NAME-->
          <div class="col-lg-12">
            <%= form.text_field :name, id: :product_name, class:'form-control' %>
            <p class="validate-new-product" id="error--name"></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row mb-4">
      <!-- categories -->
      <div class="col-lg-4">            
          <div class="row">
            <!--label for CATEGORY-->
            <div class="col-lg-12 label-new-product">
              <%= form.label :category %>
            </div>
          </div>   
          
          <div class="row">
            <!--input for CATEGORY-->
            <div class="col-lg-12">
                <%= form.collection_select(:category_id, @categories, :id, :name, {prompt: t(:select_category)}, id: 'product_product_category') %>
                <p class="validate-new-product" id="error--product--cate"></p>
              <%# <input type="text" id="product_product_category"> %>
            </div>
          </div>       
        </div>
      <!-- end categories -->
      <div class="col-lg-4">
        <div class="row">
          <!--label for MANU DATE-->
          <div class="col-lg-12 label-new-product">
            <%= form.label :manu_date %>
          </div>
        </div>

        <div class="row">
          <!--input for MANU DATE-->
          <div class="col-lg-12">
            <%= form.date_field :manu_date, id: :product_manu_date %>
            <p class="validate-new-product" id="error--date--manufacture"></p>
          </div>
        </div>
      </div>

      <div class="col-lg-4">
        <div class="row">
          <!--label for EXP DATE-->
          <div class="col-lg-12 label-new-product">
            <%= form.label :expired_date %>
          </div>
        </div>

        <div class="row">
          <!--input for EXP DATE-->
          <div class="col-lg-12">
            <%= form.date_field :expired_date, id: :product_expired_date %>
            <p class="validate-new-product" id="error--date--expiration"></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-4">
        <!--label for PICTURE-->
        <div class="row">
          <div class="col-lg-12 label-new-product">Picture</div>
        </div>
        <!--input for PICTURE-->
        <div class="row">
          <div class="col-lg-12">
            <div class="row mt-2 justify-content-center" id="product_img_field_container"> 
              <div class="M-img-field">
                  <button class='btn btn-dark M-btn-image'><i class="fa fa-image fa-3x"></i></br>Add Image</button>
                  <%= form.file_field :images, multiple: false, name: "images[url][]", class: "M-image-input", onchange:"previewProductImages(event)" %>
                  <div class="M-image-output" style="background-image: url('<%= asset_url @product.images.first.url%>'); display:block;">
                    <div class='btn btn-light M-image-remove' onclick='removeProductImages(event, <%= @product.images.first.id%>)'><i class="fa fa-trash"></i></div>
                  </div>
              </div>
            </div>
            <div class="row justify-content-center">
              <p class="validate-new-product" id="error--pic"></p>
            </div>
          </div>
           <!--input for PICTURE-->
        </div>
      </div>

      <div class="col-lg-8">
        <div class="row mb-2">
          <div class="col-lg-8">
              <div class="row">
                <!--label for MANUFACTURE-->
                <div class="col-lg-12 label-new-product">
                  <%= form.label :manufacturer %>
                </div>
              </div>
  
              <div class="row">
                <!--input for MANUFACTURE-->
                <div class="col-lg-12">
                  <%= form.text_field :manufacturer, id: :product_manufacturer %>
                  <p class="validate-new-product" id="error--manufacturer"></p>
                </div>
              </div>
            </div>
          <div class="col-lg-4">
            <div class="row">
              <!--label for STATUS-->            
              <div class="col-lg-12 label-new-product">
                <%= form.label :status %>
              </div>
            </div>
            
            <div class="row">
              <!--input for STATUS-->
              <div class="col-lg-12">
                <%= form.text_field :status, id: :product_status, readonly: true %>
              </div>
            </div>
          </div>
        </div>

        <div class="row mb-2">
          <!-- product key -->
          <div class="col-lg-12">
              <div class="row">
                <!--label for PRODUCT KEY-->
                <div class="col-lg-12 label-new-product">
                  <%= form.label :product_key %>
                </div>
              </div>
            
              <div class="row">
                <!--input for PRODUCT KEY-->
                <div class="col-lg-12">
                  <%= form.text_field :product_key, id: :product_product_key, class:'form-control' %>
                  <p class="validate-new-product" id="error--product--key" style="color: red;"><%= @product.errors[:product_key].first %></p>
                </div>
              </div>
            </div>
          <!-- end product key --> 
        </div>
        <div class="row mb-2">
          <div class="col-lg-6">            
            <div class="row">
              <!--label for PRICE-->
              <div class="col-lg-12 label-new-product">
                <%= form.label :price %>
              </div>
            </div>   
            
            <div class="row">
              <!--input for PRICE-->
              <div class="col-lg-12">
                <%= form.text_field :price, id: :product_price %>
                <p class="validate-new-product" id="error--price"></p>
              </div>
            </div>       
          </div>

          <div class="col-lg-6">
            <div class="row">
              <!--label for QUANLITY-->            
              <div class="col-lg-12 label-new-product">
                <%= form.label :quantity %>
              </div>
            </div>
            
            <div class="row">
              <!--input for QUANLITY-->
              <div class="col-lg-12">
                <%= form.text_field :quantity, id: :product_quantity %>
                <p class="validate-new-product" id="error--quantity"></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-12 label-new-product">
              <%= form.label :description %>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <%= form.text_area :description, id: :product_description, rows: 8 %>
              <p class="validate-new-product" id="error--editor"></p>
            </div>
          </div>
        </div>
      </div>


    <center>
      <div class="actions mt-5">
        <%= form.hidden_field :updater_id, id: :product_updater_id, value: current_account.id %>
        <%= form.submit class:"bnt-creat-product" %>
      </div>
    </center>
  <% end %>
</div>

app/views/products/index.html.erb
<p id="notice"></p>
<!--use css of index categories-->
<div class="wrap-index-category">
  <div class="title-index-category mb-4">
    View All Products
  </div>
  <%= paginate @products, theme: 'twitter-bootstrap-4' %>

  <!--FILTER form-->
  <%= form_with(model: @product, local: true, method: 'get', class:"filter-index-product mb-4") do |form| %>
  <!-- <form class="filter-index-product mb-4"> -->
    <div class="row">
      <!--SORT by status-->
      <div class="col-lg-3 my-2">
      <%= form.select :status, [['Active', 'active'], ['Hidden', 'hidden']], {prompt: 'Find By Status'}, id: 'select_status',class:"filter-select-index-product input-filter-index-category custom-select" %>
      </div>

      <!--SORT by CATE-->
      <div class="col-lg-3 my-2">
        <%= form.collection_select(:category_id, @categories, :id, :name, {prompt: 'Find By Category'}, id: 'select_category', class:'filter-select-index-product input-filter-index-category custom-select') %>
      </div>
  
      <!--input for SEARCH name-->
      <div class="col-lg-3 my-2">
        <!-- <input type="text" placeholder="Name..."  class="input-filter-index-category" id="txt_search_name"> -->
        <%= form.text_field :search_name, placeholder: "Name...", class:"input-filter-index-category", id: 'txt_search_name' %>
      </div>
      
      <!--submit bnt-->
      <div class="col-lg-2 my-2">
      <!-- <button class="bnt-index-category" id="M-btn-search">Find</button>e -->
        <%= form.button 'Find', type: 'button',class: "bnt-index-category", id: 'M-btn-search'%>
      </div>
    </div>
  <% end %>
  <!-- </form> -->

  <div class="wrap-table-category"><!--.wrap-table in P-index-category file-->
    <div style="min-width: 650px;">
    <!--label for tabel-->
      <div class="row pb-2 wrap-label-index-category">
      <!--KEY-->
      <div class="col-1 text-center label-index-category">No</div>
      <!--Name-->
      <div class="col-3 label-index-category">Name</div>
      <!--Category-->
      <div class="col-2 label-index-category">Category</div>
      <!--QUANTITY-->
      <div class="col-1 text-center label-index-category">Quantity</div>
      <!--STATUS-->
      <div class="col-2 text-center label-index-category">
        Status
      </div>

      <!--SHOW-->
      <div class="col-1 text-center label-index-category">Show</div>
      <!--ACTION-->
      <div class="col-2 text-center label-index-category">Action</div>
      </div>

    <!--content of table-->
    
      <% @products.each.with_index do |product, index| index += 1%>
        <% if product.quantity < 1 %>
          <div class="row py-3 wrap-content-index-product content-index-product M-test" style="color: red; font-weight: bold;">
            <!--No-->
            <div class="col-1 text-center" id="<%= product.id %>-index"><%= index %></div>
            <!--Name-->
            <div class="col-3"><%= product.name %></div>
            <!--Category-->
            <div class="col-2"><%= Category.find(product.category_id).name %></div>
            <!--QUANTITY-->
            <div class="col-1 text-center"><%= product.quantity %></div>
            <!-- STATUS-->
            <div class="col-2 text-center"><%= product.status %></div>
            <!--SHOW-->
            <div class="col-1 text-center">
              <center>
                <%= link_to product_path(product) do %>
                  <i class="fa fa-search-plus show-bnt-index-account align-items-center"></i>
                <% end %>
              </center>
            </div>

        <% else %>
          <div class="row py-3 wrap-content-index-product content-index-product M-test" id="<%= product.id %>">
            <!--No-->
            <div class="col-1 text-center" id="<%= product.id %>-index"><%= index %></div>
            <!--Name-->
            <div class="col-3"><%= product.name %></div>
            <!--Category-->
            <div class="col-2"><%= Category.find(product.category_id).name %></div>
            <!--QUANTITY-->
            <div class="col-1 text-center"><%= product.quantity %></div>
            <!-- STATUS-->
            <div class="col-2 text-center"><%= product.status.capitalize %></div>
            <!--SHOW-->
            <div class="col-1 text-center align-items-center">
              <center>
                <%= link_to product_path(product) do %>
                  <i class="fa fa-search-plus show-bnt-index-account align-items-center justify-content-center"></i>
                <% end %>
              </center>
            </div>
        <% end %>
          <!--ACTION-->
        <% if product.status == "active" %>   
          <div class="col-2">
            <center>
            <%= link_to account_product_path(current_account, product, product: {status: 'hidden'}), method: :put do %>
              <i class="fa fa-unlock-alt active-bnt-index-account align-items-center" style="width: 85%;">
                <span class="px-1 align-items-center" style="font-size: 13px;">Active</span>
              </i>
            <% end %>  
            </center>
          </div>
        <% else %>
          <div class="col-2">
            <center>
            <%= link_to account_product_path(current_account, product, product: {status: 'active'}), method: :put do %>
              <i class="fa fa-lock ban-bnt-index-account align-items-center" style="width: 85%;">
                <span class="px-1 align-items-center" style="font-size: 13px;">Ban</span>
              </i>
            <% end %>  
            </center>
          </div>
        <% end %>
      </div>
      <% end %>
    <!--content of table-->
      
      <div id="M-result"></div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    var element = document.getElementsByClassName("content-index-product");

    var i;
    for (i = 0; i < element.length; i++) {
      if (i % 2 != 0) {
        $(element[i]).css("background-color", "#F4F3EF");
      }
    }
  })
  $(document).ready(function() {
  $(window).keydown(function(event){
    if(event.keyCode == 13) {
      event.preventDefault();
      return false;
    }
  });
});
</script>

app/views/products/show.html.erb
<!--<p id="notice"><%= notice %></p>

<p>
  <strong>Product key:</strong>
  <%#= @product.product_key %>
</p>
<p>
  <strong>images</strong>
  <img src="<%#= @product.images.first.url %>" alt="">
</p>
<p>
  <strong>Name:</strong>
  <%#= @product.name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%#= @product.quantity %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%#= @product.manufacturer %>
</p>

<p>
  <strong>Manu date:</strong>
  <%#= @product.manu_date %>
</p>

<p>
  <strong>Expired date:</strong>
  <%#= @product.expired_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= simple_format(@product.description) %>
</p>

<p>
  <strong>Price:</strong>
  <%#= @product.price %>
</p>

<p>
  <strong>Status:</strong>
  <%#= @product.status %>
</p>

<%#= link_to 'Edit', edit_product_path(@product) %> |
<%#= link_to 'Back', products_path %>-->

<div class="wrap-index-category mb-2">
  <p id="notice"><%= notice %></p>
  <div class="title-index-category">
    Show Detail Product
  </div>

  <div class="row mb-4">
    <div class="col-4 ml-2">
      <%= link_to 'Back', products_path %>
      <span> || </span>
      <%= link_to 'Edit', edit_account_product_path(current_account, @product) %>
    
    </div>
  </div>

  <div class="row mb-2 justify-content-center">
    <center>
      <img src="<%= @product.images.first.url %>" alt="" class="img-show-product">
    </center>
  </div>

  <div class="row my-4">
    <div class="col-12">
      <!--NAME-->
      <div class="row">
        <div class="col-12 text-center name-show-product">
          <%= @product.name %>
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-center key-show-product" style="color:red;">
          Status: <%= @product.status.upcase %>
        </div>
      </div>
      <!--KEY-->
      <div class="row">
        <div class="col-12 text-center key-show-product">
          <%= @product.product_key %>
        </div>
      </div>
    </div>
  </div>

  <div class="row my-4">
    <div class="col-12">
      <!--content DESC-->
      <div class="row">
        <div class="col-12 text-center des-show-product">
          <%= simple_format(@product.description) %>
        </div>
      </div>
    </div>
  </div>

  <!--content-->
  <div class="row">
    <div class="col-md-1"></div>
    <!--date of manufactor-->
    <div class="col-md-2">
      <div class="row">
        <div class="col-12 text-center content-show-product"><%= @product.manu_date %></div>
      </div>

      <div class="row">
        <div class="col-12 text-center label-show-product">Date Of Manufactor</div>
      </div>
    </div>

    <!--expiration date-->
    <div class="col-md-2">
      <div class="row">
        <div class="col-12 text-center content-show-product"><%= @product.expired_date %></div>
      </div>

      <div class="row">
        <div class="col-12 text-center label-show-product">Expiration Date</div>
      </div>
    </div>

    <!--manufactor-->
    <div class="col-md-2">
      <div class="row">
        <div class="col-12 text-center content-show-product"><%= @product.manufacturer %></div>
      </div>

      <div class="row">
        <div class="col-12 text-center label-show-product">Manufacturer</div>
      </div>
    </div>

    <!--price-->
    <div class="col-md-2">
      <div class="row">
        <div class="col-12 text-center content-show-product"><%= @product.price %></div>
      </div>

      <div class="row">
        <div class="col-12 text-center label-show-product">Price</div>
      </div>
    </div>

    <!--quantity-->
    <div class="col-md-2">
      <div class="row">
        <div class="col-12 text-center content-show-product"><%= @product.quantity %></div>
      </div>

      <div class="row">
        <div class="col-12 text-center label-show-product">Quantity</div>
      </div>
    </div>

    <div class="col-md-1"></div>
  </div>
</div>