config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts,  controllers: {
    sessions: 'accounts/sessions',
    passwords: 'accounts/passwords',
    # registrations: 'accounts/registrations',
  }
  resources :accounts, except: :destroy do
    resources :categories, only: [:new, :edit, :update, :destroy, :create]  do 
      resources :images, only: [:create, :edit, :update, :show, :destroy]
    end
    resources :products, only: [:new, :edit, :update, :destroy, :create] do
      resources :images, only: [:create, :edit, :update, :show, :destroy]
    end
    resources :orders, only: [:update, :edit]
  end
  resources :products, only: [:index, :show]
  resources :categories, only: [:index]
  # resources :order_products
  resources :orders, only: [:index, :show]
  # resources :roles

  get '/change_password/:id/new', to: 'accounts#edit_change_password', as: 'change_password'
  post '/change_password/:id', to:'accounts#change_password'

  get '/home', to: 'products#home', as: "home" 
  # post '/change_pass' 
  devise_scope :account do
    root "accounts/sessions#new"
  end
#---------------Ajax---------------
  get '/account_by_role', to: 'accounts#search_accounts_by_role'
  get '/account_by_name', to: 'accounts#search_accounts_by_name'

  get '/products_by_status', to: "products#search_products_by_status"
  get '/products_by_category', to: "products#search_products_by_category"
  get '/products_by_name', to: "products#search_products_by_name"

  get '/categories_by_name', to: "categories#search_categories_by_name"

  get '/orders_by_status', to: 'orders#seach_orders_by_status'
  get '/orders_by_code', to: 'orders#search_orders_by_code'

#---------------Mobile api---------------
  namespace :api do
    namespace :v1 do
      # accounts
      resources :accounts, only: [:edit, :update, :show] 

      post "change_password", to: "accounts#change_password"
      devise_scope :account do
        post "sign_up", :to => 'registrations#create'
        post "sign_in", :to => 'sessions#create'
        post "forgot_password", to: 'passwords#forgot'
        post "reset_password", to: 'passwords#reset'
        # put 'password/update', to: 'password#update'
        delete "sign_out", :to => 'sessions#destroy'
      end
      # order products
      resources :orders, only: [:create, :destroy]
      get 'lists_orders/:account_id/:status', to: 'orders#index_orders_by_account_id' # find list orders by account id and status pending
      get 'order_details/:order_id', to: 'order_products#index_order_products_by_order_id'
      # resources :order_products, only: [:create]
      # categories
      resources :categories, only: [:index]
      get 'search_category_name/:category_name', to: "categories#search_categories_by_name"      
      #products
      resources :products, only: [:show, :index]
      get 'list_products_low_price', to: "products#index_products_by_price" #get low price 
      get 'list_products/:category_id', to: "products#index_products_by_category_id"  #find list product by category id
      get 'products_barcode/:product_key', to: "products#search_barcode"
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="M--bootstrap--templates">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SsmMarket-Web</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrap-admin-page">
      <div id="sidebar">
        <div class="adminpage-logo py-4 mb-2">SSM Admin Page</div>

        <div class="account-admin-page" onclick="dropDownAdPage()">
          <div class="row align-items-center justify-content-center">
            <i class="fa fa-address-card"></i>
            <span class="px-2">Hello, <%= current_account.name %></span>
            <i class="fa fa-angle-down change-icon"></i>
          </div>

          <ul id="dropdown-admin-page" class="dropdown-content-adpage mb-0">
            <!-- not done -->
            <li><%= link_to 'Profile', edit_account_path(current_account), class:"dropdown-detail" %></li> 
            <li><%= link_to 'Change Password', change_password_path(current_account), class:"dropdown-detail" %></li>
            <!-- not done -->
            <li><%= link_to 'Logout', destroy_account_session_path, class:"dropdown-detail", method: 'delete' %></li>
          </ul>
        </div>

        <ul class="nav">
          <li class="nav-li-admin-page mt-4">
            <%= link_to root_path, class:"slidebar-field" do %>
              <i class="fa fa-columns"></i>
              <span>DASHBOARD</span>
            <% end %>
          </li>

          <li class="nav-li-admin-page slidebar-field" onclick="dropContentMenu('dropdown-user-adminpage', 1)">
            <i class="fa fa-users"></i>
            <span>USER</span>
            <i class="fa fa-angle-down change-icon"></i>

            <ul id="dropdown-user-adminpage" class="dropdown-content-adpage mb-0">
              <li><%= link_to 'View All User', accounts_path, class:"dropdown-detail" %></li>
              <li><%= link_to 'Add Administrator', new_account_path, class:"dropdown-detail" %></li>
            </ul>
          </li>

          <li class="nav-li-admin-page slidebar-field" onclick="dropContentMenu('dropdown-product-adminpage', 2)"> 
            <i class="fa fa-shopping-cart"></i>
            <span>PRODUCT</span>
            <i class="fa fa-angle-down change-icon"></i>

            <ul id="dropdown-product-adminpage" class="dropdown-content-adpage mb-0">
              <li><%= link_to 'View All Products', products_path, class:"dropdown-detail" %></li>
              <li><%= link_to 'Add Product', new_account_product_path(current_account), class:"dropdown-detail" %></li>
            </ul>
          </li>

          <li class="nav-li-admin-page">
            <%= link_to orders_path, class:"slidebar-field" do %>
              <i class="fa fa-address-book"></i>
              <span>ORDER</span>

              <ul class="dropdown-content-adpage mb-0"></ul>
            <% end %>
          </li>

          <li class="nav-li-admin-page slidebar-field" onclick="dropContentMenu('dropdown-category-adminpage', 3)">
            <i class="fa fa-archive"></i>
            <span>CATEGORY</span>
            <i class="fa fa-angle-down change-icon"></i>

            <ul id="dropdown-category-adminpage" class="dropdown-content-adpage mb-0">
              <li><%= link_to 'View All Categories', categories_path, class:"dropdown-detail" %></li>
              <li><%= link_to 'Add Category', new_account_category_path(current_account), class:"dropdown-detail" %></li>
            </ul>
          </li>
        </ul>
      </div>

      <div class="content-admin-page">
        <div id="content-collapse">
          <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
              <button type="button" id="sidebarCollapse" class="btn" style="outline: none;">
                <i class="fa fa-bars icon-collapse"></i>
              </button>
            </div>
          </nav>
        </div>

        <div class="wrap-content-page">
        <input type="hidden" value="<%=current_account.id %>" id="txt_current">
          <%= yield %>
        </div>
      </div>
    </div>

    <!-- Dark Overlay element -->
    <div class="overlay"></div>
  </body>
  <script>
    $(document).ready(function() {
      var ele = document.getElementsByClassName("active")[0];
      $(ele).removeClass("active");

      ele = document.getElementsByClassName("nav-li-admin-page");

      var pgurl = window.location.href;

      if (pgurl.includes("home")) {
        $(ele[0]).addClass("active");
      } else if (pgurl.includes("accounts") && !pgurl.includes("categories") && !pgurl.includes("products")) {
        if (!pgurl.includes("edit")) $(ele[1]).addClass("active");
      } else if (pgurl.includes("products")) {
        $(ele[2]).addClass("active");
      } else if (pgurl.includes("orders")) {
        $(ele[3]).addClass("active");
      } else if (pgurl.includes("categories")) {
        $(ele[4]).addClass("active");
      }
    })
  </script>
</html>